name: tobeto_pair_one_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.7
  firebase_auth: ^4.17.7
  firebase_core: ^2.26.0
  flutter:
    sdk: flutter
  flutter_launcher_icons:  
  flutter_bloc: ^8.1.4
  smooth_page_indicator:
  shared_preferences: ^2.2.2
  video_player: ^2.8.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/tobeto_icon.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
 
